// Code generated by "stringer -type=Type"; DO NOT EDIT.

package dsl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Comment-1]
	_ = x[GroupBegin-2]
	_ = x[GroupEnd-3]
	_ = x[Separator-4]
	_ = x[VariableBegin-5]
	_ = x[VariableEnd-6]
	_ = x[VariableNamespace-7]
	_ = x[FunctionBegin-8]
	_ = x[FunctionEnd-9]
	_ = x[String-10]
	_ = x[Boolean-11]
	_ = x[Number-12]
	_ = x[Float-13]
}

const _Type_name = "CommentGroupBeginGroupEndSeparatorVariableBeginVariableEndVariableNamespaceFunctionBeginFunctionEndStringBooleanNumberFloat"

var _Type_index = [...]uint8{0, 7, 17, 25, 34, 47, 58, 75, 88, 99, 105, 112, 118, 123}

func (i Type) String() string {
	i -= 1
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
