before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/alto
    id: alto
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: 386
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
signs:
  - artifacts: all
release:
  prerelease: auto
  name_template: "v{{ .Version }}"
  mode: append
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE
      - README.md